version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    container_name: "financial-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
  
  api:
    build: .
    container_name: "financial-api"
    environment:
      RW_TIMEOUT: 15
      IDLE_TIMEOUT: 15
      SERVER_TIMEOUT: 15
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail http://localhost:8080/alive || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
